---
# - name:
#   include: service_create.yml
#   vars:
#     name:
#     type:
#     description:

- name: 'Create keystone service "{{ name }}"'
  shell: |
    openstack service create --name {{ name }} --description "{{ description }}" {{ type }}

  environment: token_auth_env
  run_once: True

