---
# handlers file for ansible-role-openstack-controller
- name: restart pacemaker
  service: name=pacemaker state=restarted

- name: restart httpd
  service: name=httpd state=restarted

- name: restart haproxy
  service: name=haproxy state=restarted
  tags: haproxy

- name: restart glance-api
  service: name=openstack-glance-api state=restarted

- name: restart glance-registry
  service: name=openstack-glance-registry state=restarted

- name: restart nova
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api

- name: restart horizon
  service: name={{ item }} state=restarted
  with_items:
    - httpd

- name: restart cinder
  service: name={{ item }} state=restarted
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler

- name: restart cinder volume
  service: name={{ item }} state=restarted
  with_items:
    - openstack-cinder-volume
